CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE click
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    country    VARCHAR(50)                             NOT NULL,
    user_agent VARCHAR(50)                             NOT NULL,
    referer    VARCHAR(50)                             NOT NULL,
    link_id    BIGINT,
    CONSTRAINT pk_click PRIMARY KEY (id)
);

CREATE TABLE domain
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    domain_url VARCHAR(30)                              NOT NULL,
    CONSTRAINT pk_domain PRIMARY KEY (id)
);

CREATE TABLE link
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(100),
    back_half       VARCHAR(100)                            NOT NULL,
    user_id         VARCHAR(255)                            NOT NULL,
    domain_id       INTEGER                                 NOT NULL,
    destination_url VARCHAR(100)                            NOT NULL,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    expires_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    active          BOOLEAN,
    CONSTRAINT pk_link PRIMARY KEY (id)
);

CREATE TABLE link_tags
(
    link_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    CONSTRAINT pk_link_tags PRIMARY KEY (link_id, tag_id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE role
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE tag
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(50)                             NOT NULL,
    user_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id INTEGER      NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id       VARCHAR(255) NOT NULL,
    name     VARCHAR(40)  NOT NULL,
    email    VARCHAR(70)  NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE domain
    ADD CONSTRAINT uc_domain_domainurl UNIQUE (domain_url);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE link
    ADD CONSTRAINT uk_domain_backhalf UNIQUE (domain_id, back_half);

ALTER TABLE tag
    ADD CONSTRAINT uk_user_tag_name UNIQUE (name, user_id);

CREATE INDEX idx_link_id_created_at ON click (link_id, created_at);

ALTER TABLE click
    ADD CONSTRAINT FK_CLICK_ON_LINK FOREIGN KEY (link_id) REFERENCES link (id);

ALTER TABLE link
    ADD CONSTRAINT FK_LINK_ON_DOMAIN FOREIGN KEY (domain_id) REFERENCES domain (id);

ALTER TABLE link
    ADD CONSTRAINT FK_LINK_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_user_id ON link (user_id);

ALTER TABLE tag
    ADD CONSTRAINT FK_TAG_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE link_tags
    ADD CONSTRAINT fk_link_tags_on_link_entity FOREIGN KEY (link_id) REFERENCES link (id);

ALTER TABLE link_tags
    ADD CONSTRAINT fk_link_tags_on_tag_entity FOREIGN KEY (tag_id) REFERENCES tag (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_roles_entity FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user_entity FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO role (name)
VALUES ('ROLE_USER'),
       ('ROLE_ADMIN');